#!bin/python3
import os

def edobox(args):
	# check if the command exists inside edobox.
	finalcommand = ""
	for i in args:
		finalcommand += f"{i} "
	print(finalcommand)
	if os.path.exists(f'/mnt/EdOLinux/bin/{finalcommand.split(" ")[0]}'):
		os.system(f'/mnt/EdOLinux/bin/{finalcommand.split(" ")[0]} {finalcommand.split(" ")[1]}')
	else: print("edo-box/bash: Command was not found.")

os.system('clear')
while True:
	command = input("root@edobox-linux:/$ ")
	if (command.split(' ')[0]):
		edobox(command.split(' '))
