#!bin/python3
import os

def edobox(command):
  # check if the command exists inside edobox.

os.system('clear')
while True:
  command = input("root@edobox-linux:/$ ");
  if (command.split(' ')[0]) {
    print("Unknown query.")
  }
